[package]
name = "termkey"
version = "0.17.5"
authors = ["Ben Longbons <b.r.longbons@gmail.com>"]
build = "build.rs"

[lib]
name = "termkey"
test = false

[[test]]
name = "integration"

[dependencies]
bitflags = "0.3.2"
libc = "0.1.10"
