[package]
name = "termkey"
version = "0.17.5"
authors = ["Ben Longbons <b.r.longbons@gmail.com>"]
build = "build.rs"

[lib]
name = "termkey"
test = false

[[test]]
name = "integration"
path = "src/test.rs"

[dependencies]
bitflags = "*"
